name: dpx
version: 0.2.0
description: Easily install and execute Dart package binaries with one command.
repository: https://github.com/Workiva/dpx

environment:
  sdk: '>=2.19.0 <4.0.0'

executables:
  dpx:

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  cli_util: ^0.4.0
  io: ^1.0.4
  path: ^1.8.3
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  dependency_validator: ^4.1.0
  lints: ^2.0.1
  test: ^1.24.3
  workiva_analysis_options: ^1.4.1
