name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  dart:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows ]
        sdk: [ 2.19.6, stable ]
    name: Dart ${{ matrix.sdk }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Analysis
        run: dart analyze
      - name: Formatting
        if: ${{ matrix.sdk == 'stable' && matrix.os == 'ubuntu' }}
        run: dart run format --output-none --set-exit-if-changed .
      - name: Tests
        run: dart test
